version: "3.9"

services:

    server:
        container_name: server
        image: server
        restart: always
        depends_on:
            - mongo
        build:
            context: ./server
            dockerfile: Dockerfile
            target: base
        ports:
            - "5000:5000"
        env_file: ./config.env
        volumes:
            - ./server/:/usr/src/app
            - /usr/src/app/node_modules
        networks:
            - app-network

    client:
        container_name: client
        image: client
        restart: always
        depends_on:
            - server
        links:
            - server
        build:
            context: ./client
            dockerfile: Dockerfile
            target: base
        command: npm start
        ports:
            - "3000:3000" # run this on port 80 on a web server e.g. "3000:80"
            
        volumes:
            - ./client/:/usr/app
            - /usr/app/node_modules
        networks:
            - app-network

    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db
        networks:
            - app-network

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - "8081:8081"
        depends_on:
            - mongo
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD:  
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data:
    node_modules:
    web-root:
      driver: local