version: "3.9"

services:
    server:
        container_name: server
        image: server
        restart: always
        build:
            context: .
            dockerfile: server/Dockerfile
            target: base
        ports:
            - 5000:5000
        env:
          - MONGODB_URI: <add-mongo-db-uri-here>
          - PORT: 5000
    client:
        container_name: client
        image: client
        restart: always
        build:
            context: .
            dockerfile: client/Dockerfile
            target: base
        ports:
            - 3000:80